services:
  postgres-weather:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d


  #redis-weather:
  #  image: redis/redis-stack:latest
  #  restart: always
  #  ports:
  #    - "6379:6379"
  #    - "8001:8001"
  #  volumes:
  #    - redisdata:/data

  pgadmin-weather:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres-weather
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  pgdata:
  #redisdata:
  pgadmin_data:
